# Generated by Django 5.2.5 on 2025-09-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanapplication_assets_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
